- name: Update repositories cache and install package
  apt:
    update_cache: yes
    name: "python-pip"
    state: latest
  become: yes


- name: Install latest python-pip
  apt:
    name: python-pip
    state: latest
  become: yes

- name: Pip install docker-compose
  pip:
    name:
      - docker
      - requests>=2.20.1
      - docker-compose
  become: yes